
file_path:
  C:\Users\sachi\Documents\data-science\prospa

#list of input file containing data, here sequence of file is same as table loading seq.
file_name:
  - part
  - region
  - nation
  - supplier
  - customer
  - partsupp
  - orders
  - lineitem

filename_suffix:
  TBL

info_threshold:
  6000

insert_query:
  part:
    INSERT INTO PART (P_PARTKEY ,P_NAME ,P_MFGR ,P_BRAND , P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE  , P_COMMENT )
    VALUES (? ,? ,? ,? ,? ,? ,? ,?, ?)
  region:
    INSERT INTO REGION ( R_REGIONKEY, R_NAME, R_COMMENT)
    VALUES (?, ?, ?)
  nation:
    INSERT INTO NATION (N_NATIONKEY, N_NAME, N_REGIONKEY ,  N_COMMENT)
    VALUES  ( ?, ? , ? ,?)
  supplier:
    INSERT INTO SUPPLIER (S_SUPPKEY,S_NAME,S_ADDRESS ,S_NATIONKEY ,S_PHONE ,S_ACCTBAL ,S_COMMENT)
    VALUES (? ,? ,? ,? ,? ,? ,?)
  customer:
    INSERT INTO CUSTOMER  (C_CUSTKEY ,C_NAME,C_ADDRESS,C_NATIONKEY,C_PHONE,C_ACCTBAL,C_MKTSEGMENT,C_COMMENT)
    VALUES(?,?,?,?,?,?,?,?)
  partsupp:
    INSERT INTO PARTSUPP (PS_PARTKEY,PS_SUPPKEY,PS_AVAILQTY,PS_SUPPLYCOST,PS_COMMENT)
    VALUES(?, ? ,? ,? ,?)
  orders:
    INSERT INTO ORDERS(O_ORDERKEY,O_CUSTKEY,O_ORDERSTATUS,O_TOTALPRICE,O_ORDERDATE,O_ORDERPRIORITY,O_CLERK,O_SHIPPRIORITY,O_COMMENT)
    VALUES (? ,? ,? ,? ,? ,? ,? ,?, ?)
  lineitem:
    INSERT INTO LINEITEM (L_ORDERKEY,L_PARTKEY,L_SUPPKEY,L_LINENUMBER,L_QUANTITY,L_EXTENDEDPRICE,L_DISCOUNT,L_TAX,L_RETURNFLAG,
    L_LINESTATUS,L_SHIPDATE,L_COMMITDATE,L_RECEIPTDATE,L_SHIPINSTRUCT,L_SHIPMODE,L_COMMENT)
    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)